flashcardapp/config/routes.rb
Rails.application.routes.draw do
  
  match 'drillings/create/:drill_id/:flashcard_id' => 'drillings#create', :via => :post, as: 'create_drilling'
  match 'drillings/destroy/:drill_id/:flashcard_id' => 'drillings#destroy', :via => :delete, as: 'destroy_drilling'

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end
  
  resources :flashcards, :concerns => :paginatable
  resources :drills, :concerns => :paginatable
  resources :tags
  
  get 'home/index'

  root 'home#index'

end

flashcardapp/app/models/drill.rb
class Drill < ActiveRecord::Base
    has_many :drillings
    has_many :flashcards, through: :drillings
end

flashcardapp/app/models/drilling.rb
class Drilling < ActiveRecord::Base
  belongs_to :drill
  belongs_to :flashcard
end

flashcardapp/app/models/flashcard.rb
class Flashcard < ActiveRecord::Base
    validates_presence_of :title, :answer
    has_many :taggings
    has_many :tags, through: :taggings
    has_many :drillings
    has_many :drills, through: :drillings
    
    def tag_list=(input_tags)
        # Get a unique list of strings from input
        unique_stripped_tag_names = input_tags.split(',').collect{ |str| str.strip.downcase }.uniq
        # Return a list of created/found Tags
        found_or_created_tags = unique_stripped_tag_names.collect{ |name| Tag.find_or_create_by(name: name) }
        
        self.tags = found_or_created_tags
    end
    
    def tag_list
       tags.join(', ') 
    end
end

flashcardapp/app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :taggings
    has_many :flashcards, through: :taggings
    
    def to_s
        name
    end
end

flashcardapp/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :flashcard
end

flashcardapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

flashcardapp/app/controllers/drillings_controller.rb
class DrillingsController < ApplicationController
  before_action :set_drill, only: [:create, :destroy]
  before_action :set_flashcard, only: [:create, :destroy]
  
  def create
    @drill.flashcards << @flashcard
    redirect_to edit_drill_path(@drill)
  end

  def destroy
    @drill.flashcards.destroy(params[:flashcard_id])
    redirect_to edit_drill_path(@drill)
  end
  
  private
    def set_drill
      @drill = Drill.find(params[:drill_id])
    end

    def set_flashcard
      @flashcard = Flashcard.find(params[:flashcard_id])
    end
    
    def drill_params
      params.require(:drill).permit(:name, :drill_id, :flashcard_id)
    end
end

flashcardapp/app/controllers/drills_controller.rb
class DrillsController < ApplicationController
  before_action :set_drill, only: [:show, :edit, :update, :destroy]

  # GET /drills
  # GET /drills.json
  def index
    @drills = Drill.order(:name).page(params[:page]).per(5)
  end

  # GET /drills/1
  # GET /drills/1.json
  def show
  end

  # GET /drills/new
  def new
    @drill = Drill.new
  end

  # GET /drills/1/edit
  def edit
    @drillcard_ids = @drill.flashcards.select(:id)
    @flashcards = Flashcard.where('id NOT IN (?)', @drillcard_ids)
  end

  # POST /drills
  # POST /drills.json
  def create
    @drill = Drill.new(drill_params)

    respond_to do |format|
      if @drill.save
        format.html { redirect_to @drill, notice: 'Drill was successfully created.' }
        format.json { render :show, status: :created, location: @drill }
      else
        format.html { render :new }
        format.json { render json: @drill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drills/1
  # PATCH/PUT /drills/1.json
  def update
    respond_to do |format|
      if @drill.update(drill_params)
        format.html { redirect_to @drill, notice: 'Drill was successfully updated.' }
        format.json { render :show, status: :ok, location: @drill }
      else
        format.html { render :edit }
        format.json { render json: @drill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drills/1
  # DELETE /drills/1.json
  def destroy
    @drill.destroy
    respond_to do |format|
      format.html { redirect_to drills_url, notice: 'Drill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drill
      @drill = Drill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drill_params
      params.require(:drill).permit(:name, :flashcard_id)
    end
end

flashcardapp/app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  before_action :set_flashcard, only: [:show, :edit, :update, :destroy]

  # GET /flashcards
  # GET /flashcards.json
  def index
      @flashcards = Flashcard.order(:title).page(params[:page]).per(5)
  end

  # GET /flashcards/1
  # GET /flashcards/1.json
  def show
  end

  # GET /flashcards/new
  def new
    @flashcard = Flashcard.new
  end

  # GET /flashcards/1/edit
  def edit
  end

  # POST /flashcards
  # POST /flashcards.json
  def create
    @flashcard = Flashcard.new(flashcard_params)

    respond_to do |format|
      if @flashcard.save
        format.html { redirect_to @flashcard, notice: 'Flashcard was successfully created.' }
        format.json { render :show, status: :created, location: @flashcard }
      else
        format.html { render :new }
        format.json { render json: @flashcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flashcards/1
  # PATCH/PUT /flashcards/1.json
  def update
    respond_to do |format|
      if @flashcard.update(flashcard_params)
        format.html { redirect_to @flashcard, notice: 'Flashcard was successfully updated.' }
        format.json { render :show, status: :ok, location: @flashcard }
      else
        format.html { render :edit }
        format.json { render json: @flashcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flashcards/1
  # DELETE /flashcards/1.json
  def destroy
    @flashcard.destroy
    respond_to do |format|
      format.html { redirect_to flashcards_url, notice: 'Flashcard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flashcard
      @flashcard = Flashcard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flashcard_params
      params.require(:flashcard).permit(:title, :answer, :tag_list)
    end
end

flashcardapp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @msg = "Welcome to Flashcard App"
  end
end

flashcardapp/app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def show
        @tag = Tag.find(params[:id])
    end
end

flashcardapp/app/helpers/application_helper.rb
module ApplicationHelper
end

flashcardapp/app/helpers/drillings_helper.rb
module DrillingsHelper
end

flashcardapp/app/helpers/drills_helper.rb
module DrillsHelper
end

flashcardapp/app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

flashcardapp/app/helpers/home_helper.rb
module HomeHelper
end

flashcardapp/app/helpers/tags_helper.rb
module TagsHelper
end

flashcardapp/app/views/drillings/create.html.erb
<h1>Drillings#new</h1>
<p>Find me in app/views/drillings/new.html.erb</p>

flashcardapp/app/views/drillings/destroy.html.erb
<h1>Drillings#destroy</h1>
<p>Find me in app/views/drillings/destroy.html.erb</p>

flashcardapp/app/views/drills/_form.html.erb
<%= form_for(@drill) do |f| %>
  <% if @drill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drill.errors.count, "error") %> prohibited this drill from being saved:</h2>

      <ul>
      <% @drill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h3>Name Your Flashcard Drill</h3>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

flashcardapp/app/views/drills/edit.html.erb
<h1>Editing Drill</h1>

<%= render 'form' %>

<h3>Add Flashcards to Drill</h3>
<% @flashcards.each do |flashcard| %>
    <p>
    <%= flashcard.title %>
    <%= link_to '+', create_drilling_path(@drill, flashcard), method: :post %>
    </p>
<% end %>

<h3>Remove Flashcards from Drill</h3>
<% @drill.flashcards.each do |flashcard| %>
    <p>
    <%= flashcard.title %>
    <%= link_to '+', destroy_drilling_path(@drill, flashcard), method: :delete %>
    </p>
<% end %>

<%= link_to 'Show', @drill %> |
<%= link_to 'Back', drills_path %>

flashcardapp/app/views/drills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Drills</h1>
<%= link_to 'New Drill', new_drill_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @drills.each do |drill| %>
      <tr>
        <td><%= link_to drill.name + ' (' + drill.flashcards.count.to_s + ')', drill %></td>
        <td><%= link_to 'Edit', edit_drill_path(drill) %></td>
        <td><%= link_to 'Destroy', drill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @drills %>

flashcardapp/app/views/drills/new.html.erb
<h1>New Drill</h1>

<%= render 'form' %>

<%= link_to 'Back', drills_path %>

flashcardapp/app/views/drills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @drill.name %>
</p>

<h3>Flashcards Currently in Drill</h3>
<ul>
<% @drill.flashcards.each do |flashcard| %>
    <li>
    <%= link_to flashcard.title, flashcard_path(flashcard) %>
    </li>
<% end %>
</ul>
<%= link_to 'Edit', edit_drill_path(@drill) %> |
<%= link_to 'Back', drills_path %>

flashcardapp/app/views/flashcards/_form.html.erb
<%= form_for(@flashcard) do |f| %>
  <% if @flashcard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flashcard.errors.count, "error") %> prohibited this flashcard from being saved:</h2>

      <ul>
      <% @flashcard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :minlength => 1 %>
  </div>
  <div class="field">
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_area :answer, value: @flashcard.answer %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

flashcardapp/app/views/flashcards/edit.html.erb
<h1>Editing Flashcard</h1>

<%= render 'form' %>

<%= link_to 'Show', @flashcard %> |
<%= link_to 'Back', flashcards_path %>

flashcardapp/app/views/flashcards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flashcards</h1>

<%= link_to 'New Flashcard', new_flashcard_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Tags</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @flashcards.each do |flashcard| %>
      <tr>
        <td><%= link_to flashcard.title, flashcard %></td>
        <td>
          <% flashcard.tags.each do |tag| %>
            <%= link_to tag.name, tag_path(tag) %>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_flashcard_path(flashcard) %></td>
        <td><%= link_to 'Destroy', flashcard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @flashcards %>

flashcardapp/app/views/flashcards/new.html.erb
<h1>New Flashcard</h1>

<%= render 'form' %>

<%= link_to 'Back', flashcards_path %>

flashcardapp/app/views/flashcards/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @flashcard.title %></h1>
<p><%= @flashcard.answer %></p>

<%= link_to 'Edit', edit_flashcard_path(@flashcard) %> |
<%= link_to 'Back', flashcards_path %>

flashcardapp/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<p><%= @msg %></p>

flashcardapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashcardapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Flashcards', flashcards_path %></li>
    <li><%= link_to 'Drills', drills_path %></li>
  </ul>
</nav>
<%= yield %>
<footer>
  <p>Copyright &copy; 2015 Samuel Bristol.</p>
</footer>
</body>
</html>

flashcardapp/app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Flashcards tagged with <%= @tag.name %></h1>
<ul>
  <% @tag.flashcards.each do |flashcard| %>
    <li><%= link_to flashcard.title, flashcard_path(flashcard) %></li>
  <% end %>
</ul>

<%= link_to 'Back', flashcards_path %>